Updated beagle wrapper for pearcey, pearcey rc file

diff --git a/scripts/beaglew b/scripts/beaglew
--- a/scripts/beaglew
+++ b/scripts/beaglew
@@ -11,7 +11,7 @@ set -e -o pipefail
 
 # Find original directory of bash script, resovling symlinks
 # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in/246128#246128
-
+if [ -z "${BEAGLE_HOME}" ]; then
 SOURCE=$(which beagle || echo -n)
 if [ -z "$SOURCE" ]; then
 	echo "'beagle' not found on the PATH, exiting." >&2
@@ -24,8 +24,13 @@ while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symli
     [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
 done
 DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
-JAR_DIR=$DIR
-BEAGLE_JAR="${JAR_DIR}/beagle.jar"
+BEGLE_HOME=$DIR
+fi
+BEAGLE_JAR="${BEAGLE_HOME}/beagle.jar"
+if [ ! -f "${BEAGLE_JAR}" ]; then
+    echo "Could not locate 'beagle.jar' in ${BEAGLE_HOME}, exiting." >&2
+    exit 1
+fi
 
 JAVA=java
 if [ -e "$JAVA_HOME/bin/java" ]; then
